/* Database - Schema - Tables Creation 
Here We use SuperStore Sales data From Kaggle. 
The following Code depicts the building database setup
DB
 --- L1_Bronze
    --- RAW TABLE
 --- L2_Silver
    --- CLEAN TABLE
 --- L3_GOLD (Schema with Dimension and facts table)
    --- CUSTOMER DIM TABLE
    --- PRODUCT DIM TABLE
    --- SHIPMENT DIM TABLE
    --- DATE DIM TABLE
    --- ORDER FACT TABLE
*/

-- Creating Database
CREATE DATABASE IF NOT EXISTS SUPERSTORE_SALES;


-- Creating Schemas - 3: Bronze - Silver - Gold
CREATE SCHEMA IF NOT EXISTS SUPERSTORE_SALES.L1_BRONZE;
CREATE SCHEMA IF NOT EXISTS SUPERSTORE_SALES.L2_SILVER;
CREATE SCHEMA IF NOT EXISTS SUPERSTORE_SALES.L3_GOLD;


-- Creating Tables at L1_Bronze Stage
CREATE OR REPLACE TRANSIENT TABLE SUPERSTORE_SALES.L1_BRONZE.SS_Sales_Raw
(
  Order_ID STRING,
  Order_Date STRING,
  Ship_Date STRING,
  Ship_Mode STRING,
  Customer_ID STRING,
  Customer_Name STRING,
  Segment STRING,
  Country STRING,
  City STRING,
  State STRING,
  Postal_Code STRING,
  Region_Area STRING,
  Product_ID STRING,
  Category STRING,
  Sub_Category STRING,
  Product_Name STRING,
  Sales FLOAT,
  Quantity INT,
  Discount FLOAT,
  Profit FLOAT
); 

-- Create a table in silver to hold cleaned data
CREATE OR REPLACE TABLE SUPERSTORE_SALES.L2_SILVER.SS_Sales_Clean
(
  Order_ID STRING,
  Order_Date DATE,
  Ship_Date DATE,
  Ship_Mode STRING,
  Customer_ID STRING,
  Customer_Name STRING,
  Segment STRING,
  Country STRING,
  City STRING,
  State STRING,
  Postal_Code STRING,
  Region_Area STRING,
  Product_ID STRING,
  Category STRING,
  Sub_Category STRING,
  Product_Name STRING,
  Sales FLOAT,
  Quantity INT,
  Discount FLOAT,
  Profit FLOAT
);

/* Converting the Clean tables into dimensions and facts table
Applying Star Schema approach 
-- Creating Dimension tables - Customer, Product, Shipment, Date
*/

-- Customer Dimension table
CREATE OR REPLACE TABLE SUPERSTORE_SALES.L3_GOLD.SS_CUSTOMER_DIM
(
    CUSTOMER_ID VARCHAR PRIMARY KEY, -- business key
    CUSTOMER_NAME VARCHAR,
    SEGMENT VARCHAR,
    COUNTRY VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    POSTAL_CODE VARCHAR,
    REGION_AREA VARCHAR
);

-- Product Dimension Table
CREATE OR REPLACE TABLE SUPERSTORE_SALES.L3_GOLD.SS_PRODUCT_DIM
(
  PRODUCT_ID VARCHAR PRIMARY KEY,    -- business key
  CATEGORY VARCHAR,
  SUB_CATEGORY VARCHAR,
  PRODUCT_NAME VARCHAR
);

-- Shipment Dimension Table
CREATE OR REPLACE TABLE SUPERSTORE_SALES.L3_GOLD.SS_SHIPMENT_DIM
(
  SHIP_MODE_ID NUMBER AUTOINCREMENT(101,1) PRIMARY KEY,    -- business key
  SHIP_MODE VARCHAR
);

-- Date Dimension Table
CREATE OR REPLACE TABLE SUPERSTORE_SALES.L3_GOLD.SS_DATE_DIM
(
  FULL_DATE DATE PRIMARY KEY,
  YEAR INT,
  MONTH INT,
  MONTH_NAME VARCHAR,
  DAY INT,
  QUARTER INT,
  WEEKDAY VARCHAR,
  IS_WEEKEND BOOLEAN
);

-- Creating Facts table Orders refrencing respective id

CREATE OR REPLACE TABLE SUPERSTORE_SALES.L3_GOLD.SS_ORDER_FACT
(
  ROW_ID NUMBER AUTOINCREMENT(1,1) PRIMARY KEY,
  ORDER_ID VARCHAR,
  ORDER_DATE DATE,
  SHIP_DATE DATE,
  SHIP_MODE_ID NUMBER,
  CUSTOMER_ID VARCHAR,
  PRODUCT_ID VARCHAR,
  SALES FLOAT,
  QUANTITY INT,
  DISCOUNT FLOAT,
  PROFIT FLOAT,
  REVENUE_BEFORE_DISCOUNT FLOAT, 
  PROFIT_MARGIN FLOAT, 
  SHIP_DURATION INT, 
  HIGH_DISCOUNT_FLAG BOOLEAN, 
  CONSTRAINT FK_ORDER_DATE FOREIGN KEY (ORDER_DATE) REFERENCES SS_DATE_DIM(FULL_DATE),
  CONSTRAINT FK_SHIP_DATE FOREIGN KEY (SHIP_DATE) REFERENCES SS_DATE_DIM(FULL_DATE),
  CONSTRAINT FK_SHIP_MODE FOREIGN KEY (SHIP_MODE_ID) REFERENCES SS_SHIPMENT_DIM(SHIP_MODE_ID),
  CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES SS_CUSTOMER_DIM(CUSTOMER_ID),
  CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES SS_PRODUCT_DIM(PRODUCT_ID)
);

-- show tables;