/* This File is to Alter the Status of the tasks created */

-- RESUME TASK 1
ALTER TASK SUPERSTORE_SALES.L1_BRONZE.L1_Pipe_Refresh RESUME

-- RESUME TASK 2
ALTER TASK SUPERSTORE_SALES.L1_BRONZE.L2_CLEAN_INSERT RESUME

-- RESUME TASK 3
ALTER TASK SUPERSTORE_SALES.L3_BRONZE.L3_LOAD_FACT_DIM_TABLE_TASK RESUME